apiVersion : apps/v1
kind: Deployment
metadata:
  name: eddiestackdotnetcoreapi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eddiestackdotnetcoreapi
  template:
    metadata:
      labels:
        app: eddiestackdotnetcoreapi 
    spec:
      containers:
        - name: eddiestackdotnetcoreapi 
          image: glasslewispipelines.azurecr.io/eddiestackdotnetcoreapi
          ports:
          - containerPort: 80